import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import NavBar from "@/components/NavBar";
import theme from "@/lib/theme";
import { ThemeProvider } from "@mui/material/styles";

import "./globals.css";
import { Box, CssBaseline } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline enableColorScheme />
            <Box
              sx={{ display: "flex", flexDirection: "column", height: "100vh" }}
            >
              <NavBar />
              <Box
                sx={{
                  flexGrow: 1,
                  maxWidth: "xl",
                  alignItems: "center",
                  justifyContent: "center",
                  display: "flex",
                  width: "100%",
                  marginX: "auto",
                }}
              >
                {children}
              </Box>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
