import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SignInButton from "@/components/SignInButton";
import { getSession } from "@/auth";
import GiftIcon from "@/icons/Gift";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  console.log(session?.user.name);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex overflow-hidden flex-col`}
      >
        <nav className="px-4 py-3 bg-gray-900">
          <div className="container flex justify-between items-center m-auto max-w-6xl">
            <div className="text-2xl font-light">
              <Link href="/">
                <GiftIcon /> Gift List
              </Link>
            </div>
            <div>
              <SignInButton user={session?.user} />
            </div>
          </div>
        </nav>
        <div className="justify-center items-center flex flex-1">
          {children}
        </div>
      </body>
    </html>
  );
}
