import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "@/components/NavBar";
import { Box } from "@mui/material";
import Providers from "@/components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gift List",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <Box
            sx={{ display: "flex", flexDirection: "column", height: "100vh" }}
          >
            <NavBar />
            <Box
              sx={{
                flexGrow: 1,
                maxWidth: "xl",
                alignItems: "center",
                justifyContent: "center",
                display: "flex",
                width: "100%",
                marginX: "auto",
                position: "relative",
                flexDirection: "column",
              }}
            >
              {children}
            </Box>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
