name: Lint & Format
run-name: Lint & Format
on: [push]

jobs:
  lint-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: pnpm install --frozen-lockfile
        name: Install dependencies
      - run: pnpm run lint
        name: Lint
